apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-deployment
  labels:
    app: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: wjuiceshop
    spec:
      containers:
      - name: juiceshop
        image: juiceshop:sha-72fcae8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
 ---
apiVersion: v1
kind: Service
metadata:
  name: juiceshop-service
spec:
  selector:
    app: juiceshop
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
