name: Build documentation

on:
  push:
    branches:
    - master
env:
  AWS_REGION: us-east-1
jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: ${{ secrets.DOCKER_USERNAME }}/juiceshop
        tag_with_sha: true
    - name: use klar
      run: |
        wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
        chmod +x klar
        CLAIR_ADDR=http://clair.3r1.co:6060 ./klar ${{ secrets.DOCKER_USERNAME }}/juiceshop:sha-$(git rev-parse --short HEAD)
    - name: kubernetes
      run: | 
        aws configure set default.region $AWS_REGION
        aws configure set default.output json
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        sed -i "s#IMAGE_NAME#darksyde/juiceshop#g" kustomization.yaml
        sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
        aws eks update-kubeconfig --name isen
        kubectl kustomize . | kubectl apply -f -
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: ${{ secrets.DOCKER_USERNAME }}
        target: 'https://www.example.com'
        rules_file_name: '.zap/rules.tsv'
        md_options: '-a'
